name: bson
version: 0.3.2
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ad van der Veer <advanderveer@gmail.com>
description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/priyadharsun/bson
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  fixnum: '^0.10.11'
  more: '2.3.0'

  
